name: CHECK CODE

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.18.0 ]
    steps:
      # 1. Checkout source code
      - uses: actions/checkout@v4
        with:
          path: oauth2-web
      # 2. Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: oauth2-web/package-lock.json
      # 3. Install dependencies and build
      - run: npm ci
        working-directory: oauth2-web
      - run: npm run build --if-present
        working-directory: oauth2-web
