name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.18.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      # 假设你的构建产物在 build 目录
      - name: Checkout 目标仓库
        uses: actions/checkout@v4
        with:
          repository: wlngo/oauth2
          ref: master                 # 目标分支
          token: ${{ secrets.PUSH_TOKEN }}   # 需要有推送权限的token
          path: oauth2\src\main\resources\static

      - name: 拷贝产物到目标仓库 static 目录
        run: |
          rm -rf oauth2/src/main/resources/static
          cp -r disk/* oauth2/src/main/resources/static

      - name: 推送到目标仓库
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add static
          git commit -m "自动同步静态资源: $GITHUB_SHA" || echo "No changes to commit"
          git push
